### ISSUE TITLE
Remove Platform from dependencies

### ISSUE THREAD

**Issue by warpech** [Polyjuice/GoogleSignIn#5]
This project contains "platform" in https://github.com/Polyjuice/GoogleSignIn/tree/master/src/Images/wwwroot/sys.

Plaftorm (now called webcomponents.js) should only be loaded from Starcounter installation directory.

**Comment by miyconst** [comment]
https://github.com/Polyjuice/GoogleSignIn/commit/9cb3daf4c1e60072bd5b462d9bf051b3c139c097
