### ISSUE TITLE
Warning in msbuild

### ISSUE THREAD

**Issue by warpech** [Polyjuice/GoogleSignIn#7]
When building GoogleSignIn in msbuild (I think it also happens in VS), I get the following warning:

> "c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.csproj
" (default target) (2:2) ->
(CoreCompile target) ->
  Database\GoogleProfileInfo.cs(3,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.id' is never assigned to, and will always have its default value null
 [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.cspro
j]
  Database\GoogleProfileInfo.cs(4,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.name' is never assigned to, and will always have its default value nu
ll [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.csp
roj]
  Database\GoogleProfileInfo.cs(5,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.given_name' is never assigned to, and will always have its default va
lue null [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSign
In.csproj]
  Database\GoogleProfileInfo.cs(6,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.family_name' is never assigned to, and will always have its default v
alue null [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSig
nIn.csproj]
  Database\GoogleProfileInfo.cs(7,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.link' is never assigned to, and will always have its default value nu
ll [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.csp
roj]
  Database\GoogleProfileInfo.cs(8,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.picture' is never assigned to, and will always have its default value
 null [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.
csproj]
  Database\GoogleProfileInfo.cs(9,23): warning CS0649: Field 'GoogleSignIn.Google
ProfileInfo.gender' is never assigned to, and will always have its default value
null [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.c
sproj]
  Database\GoogleProfileInfo.cs(10,23): warning CS0649: Field 'GoogleSignIn.Googl
eProfileInfo.locale' is never assigned to, and will always have its default value
 null [c:\PolyjuiceProjects\Polyjuice\GoogleSignIn\src\GoogleSignIn\GoogleSignIn.
csproj]

**Comment by miyconst** [comment]
Actually, the properties are used by the app, but the values are set via reflection:
```csharp
var info = serializer.Deserialize<GoogleProfileInfo>(text);
```

Added a controller which fills the values with `string.Empty` to rid off the warnings.
